module Ipgeobase
  API_BASE: String
  VERSION: String

  class LookupResult
    attr_reader city: String
    attr_reader country: String
    attr_reader countryCode: String
    attr_reader lat: Float
    attr_reader lon: Float
  end

  def self.build_url: (String) -> URI::Generic

  def self.lookup: (String) -> Ipgeobase::LookupResult

  def self.make_request: (URI::Generic) -> String

  def self.parse_xml: (String) -> Hash[String, Integer | Float | String]
end
